2.0
Create this sub-branch.

diff --git a/docker-entrypoint b/docker-entrypoint
--- a/docker-entrypoint
+++ b/docker-entrypoint
@@ -2,10 +2,88 @@
 
 . ~/.bashrc
 
+MACHINE_IP=$(hostname -I | awk 'NR==1 {print $1}')
+
+if [[ "$(find /usr -name libcuda.so.1 | grep -v "compat") " == " " || "$(ls /dev/nvidiactl 2>/dev/null) " == " " ]]; then
+  echo
+  echo "WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available."
+  echo "   Use 'nvidia-docker run' to start this container; see"
+  echo "   https://github.com/NVIDIA/nvidia-docker/wiki/nvidia-docker ."
+else
+  ( /usr/local/bin/checkSMVER.sh )  
+  DRIVER_VERSION=$(sed -n 's/^NVRM.*Kernel Module *\([0-9.]*\).*$/\1/p' /proc/driver/nvidia/version 2>/dev/null || true)
+  if [[ ! "$DRIVER_VERSION" =~ ^[0-9]*.[0-9]*(.[0-9]*)?$ ]]; then
+    echo "Failed to detect NVIDIA driver version."
+  elif [[ "${DRIVER_VERSION%%.*}" -lt "${CUDA_DRIVER_VERSION%%.*}" ]]; then
+    if [[ "${_CUDA_COMPAT_STATUS}" == "CUDA Driver OK" ]]; then
+      echo
+      echo "NOTE: Legacy NVIDIA Driver detected.  Compatibility mode ENABLED."
+    else
+      echo
+      echo "ERROR: This container was built for NVIDIA Driver Release ${CUDA_DRIVER_VERSION%.*} or later, but"
+      echo "       version ${DRIVER_VERSION} was detected and compatibility mode is UNAVAILABLE."
+      echo
+      echo "       [[${_CUDA_COMPAT_STATUS}]]"
+      sleep 2
+    fi
+  fi
+fi
+
+if ! cat /proc/cpuinfo | grep flags | sort -u | grep avx >& /dev/null; then
+  echo
+  echo "ERROR: This container was built for CPUs supporting at least the AVX instruction set, but"
+  echo "       the CPU detected was $(cat /proc/cpuinfo |grep "model name" | sed 's/^.*: //' | sort -u), which does not report"
+  echo "       support for AVX.  An Illegal Instrution exception at runtime is likely to result."
+  echo "       See https://en.wikipedia.org/wiki/Advanced_Vector_Extensions#CPUs_with_AVX ."
+  sleep 2
+fi
+
+DETECTED_MOFED=$(cat /sys/module/mlx5_core/version 2>/dev/null || true)
+case "${DETECTED_MOFED}" in
+  "${MOFED_VERSION}")
+    echo
+    echo "Detected MOFED ${DETECTED_MOFED}."
+    ;;
+  "")
+    echo
+    echo "NOTE: MOFED driver for multi-node communication was not detected."
+    echo "      Multi-node communication performance may be reduced."
+    ;;
+  *)
+    if /opt/mellanox/change_mofed_version.sh "${DETECTED_MOFED}" >& /dev/null; then
+      echo
+      echo "NOTE: Detected MOFED driver ${DETECTED_MOFED}; version automatically updated."
+    else
+      echo
+      echo "ERROR: Detected MOFED driver ${DETECTED_MOFED}, but this container has version ${MOFED_VERSION}."
+      echo "       Unable to automatically upgrade this container."
+      echo "       Use of RDMA for multi-node communication will be unreliable."
+      sleep 2
+    fi
+    ;;
+esac
+
+DETECTED_NVPEERMEM=$(cat /sys/module/nv_peer_mem/version 2>/dev/null || true)
+if [[ "${DETECTED_MOFED} " != " " && "${DETECTED_NVPEERMEM} " == " " ]]; then
+  echo
+  echo "NOTE: MOFED driver was detected, but nv_peer_mem driver was not detected."
+  echo "      Multi-node communication performance may be reduced."
+fi
+
+if [[ "$(df -k /dev/shm |grep ^shm |awk '{print $2}') " == "65536 " ]]; then
+  echo
+  echo "NOTE: The SHMEM allocation limit is set to the default of 64MB.  This may be"
+  echo "   insufficient for TensorFlow.  NVIDIA recommends the use of the following flags:"
+  echo "   nvidia-docker run --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 ..."
+fi
+
+echo
+
 echo "-----------------------------------"
 echo "     XUbuntu Desktop Container"
 echo "           Yuchen Jin"
-echo "nvcr.io/nvidia/tensorflow:18.08-py3"
+echo "nvcr.io/nvidia/tensorflow:19.10-py3"
+echo "          ubuntu 18.04"
 echo "-----------------------------------"
 echo "This is a ubuntu desktop based on VNC server, to understand how to use it, follow these steps:"
 echo "    S1: Input the password as the instruction."
@@ -18,15 +96,20 @@ echo "    S6: Input the password which is set in S1."
 echo "    S7: Now you would see the desktop has been launched"
 echo "    S8: Enjoy your remote desktop. Note that you should not close both the terminal running the container and the default terminal of noVNC screen."
 echo "    S9: Use \"xrandr -s 1920x1080\" to choose the resolution as you want."
-echo "        Available list: 1920x1080, 1280x720, 1366x768, 1024x768, 800x600."
 echo "    S10: Before quit from the docker, remember call \"tigervncserver -kill :1\" (or other port) outside the VNC."
 echo ""
 
 echo "---------"
 echo "Host IP:"
-hostname -I
+echo $MACHINE_IP
 echo "---------"
 
 echo "VNC settings:"
-tigervncserver -name xubuntu-tf -depth 24 -geometry 1920x1080
-exec bash
+tigervncserver -name xubuntu -depth 24 -geometry 1920x1080
+noVNC --vnc $MACHINE_IP:5901 --listen 6080
+
+if [[ $# -eq 0 ]]; then
+  exec "/bin/bash"
+else
+  exec "$@"
+fi
