1.0.1
1. Fix a bug caused by noVNC version.

diff --git a/scripts/install-vnc b/scripts/install-vnc
--- a/scripts/install-vnc
+++ b/scripts/install-vnc
@@ -4,6 +4,7 @@
 set -e
 RESET='\033[0m'
 COLOR='\033[1;32m'
+ERROR_COLOR='\033[1;31m'
 WARN_COLOR='\033[1;33m'
 
 function msg {
@@ -14,8 +15,12 @@ function warn {
   echo -e "${WARN_COLOR}$(date): $1${RESET}"
 }
 
+function msgerr {
+  echo -e "${ERROR_COLOR}$(date): $1${RESET}"
+}
+
 function fail {
-  msg "Error : $?"
+  msgerr "Error : $?"
   exit 1
 }
 
@@ -111,12 +116,22 @@ then
     msg "Install noVNC."
     cd $SOURCE_PATH || fail
     git clone https://github.com/novnc/noVNC.git || fail
-    ln -s $SOURCE_PATH/noVNC/utils/launch.sh $BUILD_PATH/noVNC || fail
+
+    if [ -f "$SOURCE_PATH/noVNC/utils/novnc_proxy" ]; then
+        ln -s $SOURCE_PATH/noVNC/utils/novnc_proxy $BUILD_PATH/noVNC || fail
+    else 
+        if [ -f "$SOURCE_PATH/noVNC/utils/launch.sh" ]; then
+            ln -s $SOURCE_PATH/noVNC/utils/launch.sh $BUILD_PATH/noVNC || fail
+        else 
+            msgerr "Fail to find the launching script in the current noVNC build, maybe the repository has a wrong version."
+            exit 1
+        fi
+    fi
 
     # Install websockify
     cd $SOURCE_PATH/noVNC/utils || fail
     git clone https://github.com/novnc/websockify websockify || fail
-    
+
     # This operation is needed when python<=3.5
     CUR_PY_VER=$(python3 /root/scripts/get-pyver.py 2>&1)
     if [ "x${CUR_PY_VER}" != "xpy36" ] && [ "x${CUR_PY_VER}" != "xpy37+" ]
